[package]
name = "monzeromer-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3.1"
futures = "0.3.29"
jsonwebtoken = "9.1.0"
mongodb = "2.7.1"
serde = "1.0.193"
shuttle-actix-web = "0.34.0"
shuttle-runtime = "0.34.0"
tokio = "1.26.0"
